### ISSUE TITLE
Won't install

### ISSUE THREAD

**Issue by DatPat** [whiteout2/x86#1] opened 2019-01-11 03:34 UTC
Hello,
I have tried using your extension but unfortunately the installation fails. I am not sure as to why but I do have visual studio code(1.30.2) installed.

The Installation log follows below:

1/11/2019 4:32:38 AM - Microsoft VSIX Installer
1/11/2019 4:32:38 AM - -------------------------------------------
1/11/2019 4:32:38 AM - Initializing Install...
1/11/2019 4:32:38 AM - Extension Details...
1/11/2019 4:32:38 AM - 	Identifier      : x86
1/11/2019 4:32:38 AM - 	Name            : x86 Instruction Reference
1/11/2019 4:32:38 AM - 	Author          : whiteout2
1/11/2019 4:32:38 AM - 	Version         : 0.1.0
1/11/2019 4:32:38 AM - 	Description     : Intel x86 instruction reference in a VS Code custom Activity Bar view
1/11/2019 4:32:38 AM - 	Locale          : en-US
1/11/2019 4:32:38 AM - 	MoreInfoURL     : 
1/11/2019 4:32:38 AM - 	InstalledByMSI  : False
1/11/2019 4:32:38 AM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
1/11/2019 4:32:38 AM - 
1/11/2019 4:32:38 AM - 	Supported Products : 
1/11/2019 4:32:38 AM - 		Microsoft.VisualStudio.Code
1/11/2019 4:32:38 AM - 			Version : 
1/11/2019 4:32:38 AM - 
1/11/2019 4:32:38 AM - 	References      : 
1/11/2019 4:32:38 AM - 
1/11/2019 4:32:38 AM - Searching for applicable products...
1/11/2019 4:32:38 AM - Found installed product - Microsoft Visual Studio Community 2013
1/11/2019 4:32:38 AM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
1/11/2019 4:32:38 AM - Found installed product - Global Location
1/11/2019 4:32:38 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by PharaohJoe** [comment] 2019-01-27 20:05
Same, but I finally figured out that it's only for the mac version of VS code. Probably why it doesn't install as I'm on Windows

**Comment by rgosens2** [comment] 2019-02-17 12:55
Installs and works as expected on macOS Sierra 10.12 and VS Code 1.31.1.
Don't know about High Sierra or Mojave.

**Comment by rgosens2** [comment] 2019-04-09 23:25
Issue confirmed and resolved in 0.3.3

Should work on Windows now too.
It was caused by colons ':' in .html filenames. 
Mac automatically changes them into slashes '/'
Windows simply refuses to write the file.
Extension now changes all colons to underscore '_'.

Tested on Windows 7 SP1 and VSCode 1.33.0

**Closed as completed** 2020-02-04 16:02 UTC
